"""HTTP and WebSocket API.

Small on purpose. Four kinds of thing are exposed:

  scene    read and write the configuration the operator sets up
  state    the live measurement, pushed over a websocket
  imagery  the current frame, the heat overlay, and stored alert evidence
  record   alert history and the audit log

Everything an operator can see about people is aggregate. There is no endpoint
that returns a track, a box, a crop of a person, or anything keyed to an
individual, because no part of the system produces one.
"""

from __future__ import annotations

import asyncio
import json
import logging
import re
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException, Request, WebSocket, WebSocketDisconnect
from fastapi.responses import HTMLResponse, JSONResponse, Response
from fastapi.staticfiles import StaticFiles

from . import settings
from .contract import BAND_LABELS, SceneConfig, SourceConfig, utcnow
from .db import Store
from .pipeline import Pipeline
from .store import LiveState
from .worker.calibration import Calibrator
from .worker.overlay import band_legend

log = logging.getLogger(__name__)

# Evidence filenames are generated by us and look like "a17". Anything else is
# refused outright rather than sanitised -- the frames directory is the only
# place the system stores imagery, and it is not a file server.
ALERT_ID = re.compile(r"^a\d+$")

NO_STORE = {"Cache-Control": "no-store, no-cache, must-revalidate", "Pragma": "no-cache"}


def default_scene() -> SceneConfig:
    """The scene used on a fresh install: the synthetic ghat, if it is present."""
    preset = settings.CONFIG_DIR / "scene.synthetic.json"
    if preset.exists():
        try:
            return SceneConfig.model_validate_json(preset.read_text(encoding="utf-8"))
        except Exception:
            log.exception("default preset is unreadable; starting unconfigured")

    return SceneConfig(
        name="Unconfigured scene",
        source=SourceConfig(kind=settings.DEFAULT_SOURCE_KIND, uri=settings.DEFAULT_SOURCE_URI),
    )


def create_app() -> FastAPI:
    settings.ensure_dirs()
    live = LiveState()
    store = Store(settings.DB_PATH)
    pipeline = Pipeline(live, store)

    @asynccontextmanager
    async def lifespan(app: FastAPI):
        scene = store.load_scene()
        if scene is None:
            scene = default_scene()
            store.save_scene(scene)
            store.audit("system", "scene.init", scene.name)
        pipeline.apply_scene(scene)
        pipeline.start()
        store.audit("system", "service.start", f"scene={scene.name}")
        log.info("ready on scene %r", scene.name)
        try:
            yield
        finally:
            store.audit("system", "service.stop")
            pipeline.stop()
            store.close()

    app = FastAPI(title="UKSI P-007 Crowd Safety Analytics", version="0.1.0", lifespan=lifespan)
    app.state.live = live
    app.state.store = store
    app.state.pipeline = pipeline

    def actor(request: Request) -> str:
        return request.client.host if request.client else "unknown"

    # -- scene ------------------------------------------------------------

    @app.get("/api/scene")
    def get_scene() -> JSONResponse:
        scene = store.load_scene() or default_scene()
        return JSONResponse(scene.model_dump(mode="json"))

    @app.post("/api/scene")
    def post_scene(scene: SceneConfig, request: Request) -> JSONResponse:
        """Replace the scene configuration and hand it to the worker.

        Every change is audited with what changed, because zone geometry and
        thresholds are exactly the settings that decide whether an alert fires.
        """
        scene.updated_at = utcnow()
        store.save_scene(scene)
        pipeline.apply_scene(scene)
        store.audit(
            actor(request), "scene.update",
            f"{scene.name}: {len(scene.zones)} zones, {len(scene.corridors)} corridors, "
            f"calibrated={scene.calibrated}",
        )
        return JSONResponse(scene.model_dump(mode="json"))

    @app.post("/api/scene/preview")
    def preview_scene(scene: SceneConfig) -> JSONResponse:
        """Compute ground areas for a scene without adopting it.

        The setup screen needs to show real square metres while the operator is
        still drawing, and it must be able to do that without the live pipeline
        lurching onto a half-finished configuration. So this touches neither the
        store nor the worker: it builds a throwaway Calibrator and measures.
        """
        if scene.calibration.is_set:
            try:
                cal = Calibrator.from_points(
                    scene.calibration.image_points, scene.calibration.world_points
                )
            except ValueError as exc:
                raise HTTPException(400, f"calibration is degenerate: {exc}") from exc
        else:
            cal = Calibrator.uncalibrated()

        warnings: list[str] = []
        if not cal.is_calibrated:
            warnings.append(
                "Not calibrated. Areas below assume 0.05 m per pixel and are indicative only."
            )
        if not scene.zones:
            warnings.append("No zones drawn, so there is nothing to measure.")
        for z in scene.zones:
            missing = [n for n in z.neighbors if n not in {o.id for o in scene.zones}]
            if missing:
                warnings.append(f"{z.name}: unknown neighbour {', '.join(missing)}")
        if scene.zones and not any(z.neighbors for z in scene.zones):
            warnings.append(
                "No zone has neighbours set, so the convergence signal cannot fire."
            )

        def measure(items) -> list[dict]:
            out = []
            for it in items:
                area = cal.area_m2(it.polygon)
                out.append({
                    "id": it.id,
                    "name": it.name,
                    "area_m2": round(area, 1),
                    # What one person standing in this zone would read as. Gives
                    # the operator a sanity check on their own calibration: if a
                    # zone the size of a room reports 4000 m2, the clicked points
                    # or the typed dimensions are wrong.
                    "density_per_person": round(1.0 / area, 4) if area > 1e-6 else None,
                })
            return out

        return JSONResponse({
            "calibrated": cal.is_calibrated,
            "zones": measure(scene.zones),
            "corridors": measure(scene.corridors),
            "total_area_m2": round(sum(cal.area_m2(z.polygon) for z in scene.zones), 1),
            "warnings": warnings,
        })

    @app.get("/api/presets")
    def list_presets() -> JSONResponse:
        out = []
        if settings.CONFIG_DIR.exists():
            for path in sorted(settings.CONFIG_DIR.glob("scene.*.json")):
                try:
                    raw = json.loads(path.read_text(encoding="utf-8"))
                    out.append({
                        "id": path.stem.removeprefix("scene."),
                        "name": raw.get("name", path.stem),
                        "zones": len(raw.get("zones", [])),
                        "source": raw.get("source", {}).get("kind", ""),
                    })
                except Exception:
                    log.warning("unreadable preset %s", path.name)
        return JSONResponse(out)

    @app.post("/api/presets/{preset_id}/apply")
    def apply_preset(preset_id: str, request: Request) -> JSONResponse:
        if not re.fullmatch(r"[A-Za-z0-9_-]+", preset_id):
            raise HTTPException(400, "bad preset id")
        path = settings.CONFIG_DIR / f"scene.{preset_id}.json"
        if not path.exists():
            raise HTTPException(404, "no such preset")
        scene = SceneConfig.model_validate_json(path.read_text(encoding="utf-8"))
        store.save_scene(scene)
        pipeline.apply_scene(scene)
        store.audit(actor(request), "scene.preset", f"{preset_id} -> {scene.name}")
        return JSONResponse(scene.model_dump(mode="json"))

    # -- live state -------------------------------------------------------

    @app.get("/api/state")
    def get_state() -> JSONResponse:
        """Polling fallback. The websocket is the real path."""
        wire = live.wire
        if wire is None:
            return JSONResponse({"status": "warming up"}, status_code=503, headers=NO_STORE)
        return JSONResponse(wire, headers=NO_STORE)

    @app.websocket("/ws/state")
    async def ws_state(ws: WebSocket) -> None:
        await ws.accept()
        who = ws.client.host if ws.client else "unknown"
        store.audit(who, "session.open", "control room view")
        interval = 1.0 / max(settings.PUBLISH_HZ, 0.1)
        last_seq = -1
        try:
            while True:
                wire = live.wire
                if wire is not None and wire.get("seq") != last_seq:
                    last_seq = wire.get("seq")
                    await ws.send_text(json.dumps(wire))
                await asyncio.sleep(interval)
        except (WebSocketDisconnect, RuntimeError, ConnectionError):
            pass
        finally:
            store.audit(who, "session.close", "control room view")

    # -- imagery ----------------------------------------------------------
    # Specific routes are declared before the evidence route so a frame name
    # can never be interpreted as an alert id.

    @app.get("/frames/latest.jpg")
    def latest_frame() -> Response:
        jpeg, seq = live.frame
        if not jpeg:
            raise HTTPException(503, "no frame yet")
        return Response(jpeg, media_type="image/jpeg", headers={**NO_STORE, "X-Frame-Seq": str(seq)})

    @app.get("/frames/heat.png")
    def heat_overlay() -> Response:
        png, seq = live.heat
        if not png:
            raise HTTPException(503, "no heat map yet")
        return Response(png, media_type="image/png", headers={**NO_STORE, "X-Heat-Seq": str(seq)})

    @app.get("/frames/{alert_id}.jpg")
    def evidence(alert_id: str, request: Request) -> Response:
        if not ALERT_ID.fullmatch(alert_id):
            raise HTTPException(400, "bad evidence id")
        path: Path = settings.FRAMES_DIR / f"{alert_id}.jpg"
        if not path.exists():
            raise HTTPException(404, "evidence expired or never captured")
        # Retrieval of a stored image is the one read worth logging: it is the
        # only point where a person's likeness, however coarse, is served.
        store.audit(actor(request), "evidence.view", alert_id)
        return Response(path.read_bytes(), media_type="image/jpeg", headers=NO_STORE)

    # -- record -----------------------------------------------------------

    @app.get("/api/alerts")
    def alerts(limit: int = 50) -> JSONResponse:
        limit = max(1, min(limit, 500))
        return JSONResponse([a.model_dump(mode="json") for a in store.recent_alerts(limit)])

    @app.get("/api/audit")
    def audit(limit: int = 100) -> JSONResponse:
        limit = max(1, min(limit, 1000))
        return JSONResponse(store.audit_tail(limit))

    # -- demo -------------------------------------------------------------

    @app.post("/api/demo/scenario")
    def demo_scenario(body: dict, request: Request) -> JSONResponse:
        """Move the simulator to a point in its scripted arc.

        A demo affordance, and nothing else. The scripted congestion takes
        around three minutes of wall clock to build, which is the whole length
        of a demo slot, so there has to be a way to arrive at the interesting
        part without dead air.

        It deliberately is not a speed multiplier. Running the simulation fast
        would scale every speed in m/s and every per-minute trend by the same
        factor, and the entire claim of this system is that those are real
        units. Better to skip forward than to lie about the numbers.
        """
        source = pipeline.source
        if source is None:
            # The worker builds its backend before it assigns the source, and
            # that can block on a first-run weight download. Saying "not
            # synthetic" here would be a lie, and telling a demo script to give
            # up would be worse.
            raise HTTPException(
                503,
                "the worker is still starting up (loading the density backend); retry shortly",
                headers={"Retry-After": "5"},
            )
        if not hasattr(source, "warm_to"):
            raise HTTPException(
                409, "the scenario clock only exists on the synthetic source"
            )

        try:
            t_s = float(body.get("t_s", 0.0))
        except (TypeError, ValueError):
            raise HTTPException(400, "t_s must be a number") from None
        if not 0.0 <= t_s <= 3600.0:
            raise HTTPException(400, "t_s must be between 0 and 3600 seconds")

        reached = source.warm_to(t_s)
        # History is measured, not simulated, so it does not survive the jump.
        # Leaving it would feed the trend estimator a step change it never saw
        # and invent a slope out of an edit.
        pipeline.reset_history()
        store.audit(actor(request), "demo.scenario", f"t={reached:.0f}s")
        return JSONResponse({"t_s": round(reached, 1), "note": "demo control"})

    @app.get("/api/meta")
    def meta() -> JSONResponse:
        """Everything the UI needs to render labels and legends consistently."""
        scene = store.load_scene() or default_scene()
        return JSONResponse({
            "legend": band_legend(),
            "band_labels": BAND_LABELS,
            "thresholds": scene.thresholds.model_dump(mode="json"),
            "sample_fps": settings.SAMPLE_FPS,
            "publish_hz": settings.PUBLISH_HZ,
            "retention": {
                "evidence_hours": settings.EVIDENCE_RETENTION_HOURS,
                "alert_days": settings.ALERT_RETENTION_DAYS,
                "audit_days": settings.AUDIT_RETENTION_DAYS,
            },
        })

    @app.get("/api/health")
    def health() -> JSONResponse:
        wire = live.wire
        src = wire.get("source") if wire else None
        return JSONResponse({
            "ok": True,
            "have_state": wire is not None,
            "source_connected": bool(src and src.get("connected")),
            "model": (wire or {}).get("model", ""),
        })

    # -- frontend ---------------------------------------------------------

    if settings.FRONTEND_DIR.exists():
        app.mount("/", StaticFiles(directory=str(settings.FRONTEND_DIR), html=True), name="ui")
    else:
        @app.get("/", response_class=HTMLResponse)
        def placeholder() -> str:
            return "<h1>UKSI P-007</h1><p>API is up. Frontend not built yet.</p>"

    return app


app: Optional[FastAPI] = None


def get_app() -> FastAPI:
    global app
    if app is None:
        app = create_app()
    return app
